version: "3.7"

services: 
    db:
        image: couchdb:2.3.1
        volumes: 
            - db_data:/opt/couchdb/data
        ports: 
            - "5984:5984"
    s3:
        image: minio/minio:RELEASE.2020-02-07T23-28-16Z
        ports: 
            - "9000:9000"
        volumes: 
            - s3_data:/data
        command: server /data
        environment: 
            MINIO_ACCESS_KEY: admin
            MINIO_SECRET_KEY: password
    
    rabbitmq:
        image: rabbitmq:3.7-alpine
        ports:
            - "5672:5672"
    app:
        build: .
        ports: 
            - "8000:8000"
        volumes: 
            - ./:/src/
        depends_on: 
            - rabbitmq

        environment: 
            PYTHONUNBUFFERED: 0
        command: bash -c "sleep 10 && nameko run --config ./config.yaml app"


volumes: 
    db_data:
    s3_data: